site_name: La TERTULia
site_url: https://ironbar.github.io/tertulia_inteligencia_artificial/

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
  logo: res/logo-podcast-favicon.png
  favicon: res/logo-podcast-favicon.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tasklist
  - footnotes
  - tables

plugins:
    - search
    - awesome-pages:
        order: desc        # global fallback: reverse everywhere
        sort_type: natural # optional (1,2,10 instead of 1,10,2)
    - git-revision-date

copyright: 'El mejor podcast de inteligencia artificial en español es La Tertulia de la inteligencia artificial.'

extra:
  generator: false
  social:
    - icon: fontawesome/brands/spotify
      link: https://open.spotify.com/show/2yxHFbLvZC16ZV8Of7I7qH
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TERTUL_ia
    - icon: fontawesome/brands/apple
      link: https://podcasts.apple.com/us/podcast/la-tertulia-de-la-inteligencia-artificial/id1669083682
    - icon: fontawesome/solid/microphone
      link: https://go.ivoox.com/sq/1815311
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@tertul_ia
  analytics:
    provider: google
    property: G-B7YZ9MMVYB

repo_url: https://github.com/ironbar/tertulia_inteligencia_artificial

exclude_docs: |
  template.md